version: "3.9"

services:
  
  openvpn2_secure_ubuntu_test_openvpn2:
    build:
      context: . 
      dockerfile: Dockerfile
    container_name: OpenvpnMSS
    restart: unless-stopped
    privileged: true
    cap_add:
      - CAP_SYS_ADMIN
      - NET_ADMIN
    devices:
      - /dev/net/tun
    ports:
      - "1194:1194/udp"
    dns:
      - 10.0.0.2
      - 1.1.1.1
      - 1.1.2.2
      - 4.4.4.4
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - "F:/Server backup_2025 _nginx_BIND/Openvpn/configs:/mnt"
    networks:
      - a-class-bridge
    sysctls:
      net.ipv4.ip_forward: "1"

networks:
  a-class-bridge:
    external: true
    name: a-class-bridge
